CREATE TABLE IF NOT EXISTS visitor_appointment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  visitor_name VARCHAR(64) NOT NULL,
  visitor_mobile VARCHAR(32) NOT NULL,
  visitor_email VARCHAR(128),
  id_type VARCHAR(32),
  id_number VARCHAR(64),
  host_id BIGINT,
  host_name VARCHAR(64),
  host_mobile VARCHAR(32),
  visit_reason VARCHAR(256),
  visit_address VARCHAR(256),
  appointment_start DATETIME NOT NULL,
  appointment_end DATETIME,
  vehicle_plate VARCHAR(32),
  status TINYINT(1) NOT NULL DEFAULT 0,
  audit_user_id BIGINT,
  audit_time DATETIME,
  audit_remark VARCHAR(256),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT(1) NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 1
);
